### ISSUE TITLE
Add configurable directory parameters

### ISSUE THREAD

**Issue by kennycason** [kennycason/kakyll#5]
```
directories:
   - name: assets
   - name: news
     render: true
```

The idea is that some directories can be copied as-is (which is faster) but some directories may have markdown/templates to render.
